/* Static build: there is no room server, so the browser that creates the room
 * runs the simulation and the two players talk to each other directly.
 * Generated by tools/build-pages.mjs - edit public/js/mode.mjs instead.
 */
export const MODE = 'p2p';
